# Pandas

In [22]:
import pandas as pd
import numpy as np

In [23]:
a = pd.Series([1, 4, 5,4, 'amirali', np.nan])
a

0          1
1          4
2          5
3          4
4    amirali
5        NaN
dtype: object

In [24]:
dates = pd.date_range('20260101', periods=6)
dates

DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04',
               '2026-01-05', '2026-01-06'],
              dtype='datetime64[ns]', freq='D')

In [25]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=["a", "b", "c", "d"])
df

                   a         b         c         d
2026-01-01  0.289070  0.067393 -0.395934  0.836731
2026-01-02 -0.795548  1.938933 -0.486407  0.498797
2026-01-03 -0.057986 -1.436297  1.289881  1.296864
2026-01-04  0.107680 -0.464987 -1.125434 -0.073114
2026-01-05  0.250464  1.413742 -0.035229 -0.112805
2026-01-06  0.286878  1.073874  2.382426  0.724961

In [26]:
df.dtypes

a    float64
b    float64
c    float64
d    float64
dtype: object

In [27]:
df["a"]

2026-01-01    0.289070
2026-01-02   -0.795548
2026-01-03   -0.057986
2026-01-04    0.107680
2026-01-05    0.250464
2026-01-06    0.286878
Freq: D, Name: a, dtype: float64

In [28]:
df.head()
df.tail()

                   a         b         c         d
2026-01-02 -0.795548  1.938933 -0.486407  0.498797
2026-01-03 -0.057986 -1.436297  1.289881  1.296864
2026-01-04  0.107680 -0.464987 -1.125434 -0.073114
2026-01-05  0.250464  1.413742 -0.035229 -0.112805
2026-01-06  0.286878  1.073874  2.382426  0.724961

In [29]:
df.describe()

              a         b         c         d
count  6.000000  6.000000  6.000000  6.000000
mean   0.013426  0.432110  0.271550  0.528573
std    0.418417  1.270805  1.308320  0.547372
min   -0.795548 -1.436297 -1.125434 -0.112805
25%   -0.016569 -0.331892 -0.463789  0.069864
50%    0.179072  0.570634 -0.215582  0.611879
75%    0.277774  1.328775  0.958604  0.808789
max    0.289070  1.938933  2.382426  1.296864

In [30]:
df.sort_values(by="b")

                   a         b         c         d
2026-01-03 -0.057986 -1.436297  1.289881  1.296864
2026-01-04  0.107680 -0.464987 -1.125434 -0.073114
2026-01-01  0.289070  0.067393 -0.395934  0.836731
2026-01-06  0.286878  1.073874  2.382426  0.724961
2026-01-05  0.250464  1.413742 -0.035229 -0.112805
2026-01-02 -0.795548  1.938933 -0.486407  0.498797

In [ ]:
# df.to_csv("tmp/test.csv")